# Generated by Django 4.0.5 on 2022-06-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Image',
            new_name='image',
        ),
    ]
